//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public int AuditId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string EventType { get; set; }
        public System.DateTime EventDateTime { get; set; }
        public string Details { get; set; }
        public string IPAddress { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
